analyzer:
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - collection_methods_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - always_declare_return_types
    - always_specify_types
    - always_use_package_imports
    - avoid_bool_literals_in_conditional_expressions
    - avoid_print
    - avoid_init_to_null
    - unnecessary_new
