name: willshex
description: All the base classes usually used for calling willshex apis plus the storage library for local persistence.
version: 0.0.1
homepage: https://www.willshex.com
publish_to: "none"

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  path: ^1.8.0
  http: ^0.13.3
  logging: ^1.0.1

dev_dependencies:
  test: ^1.17.9
